export type BroadcastPlaybackMode = 'external_only' | 'unknown';
export type BroadcastPriority = 'verified' | 'best_effort' | 'unstable';
export type BroadcastSport = 'general' | 'football' | 'basketball' | 'combat' | 'motorsport';
export type BroadcastContentType = 'news' | 'sports';

export type BroadcastSource = {
  id: string;
  name: string;
  region: string;
  country: string;
  language: string;
  category: string;
  sourceType: string;
  status: 'curated' | 'monitor';
  streamUrl: string;
  homepageUrl: string;
  notes: string;
  playbackMode: BroadcastPlaybackMode;
  tags: string[];
  priority: BroadcastPriority;
  contentType: BroadcastContentType;
  sport?: BroadcastSport;
};

export const BROADCAST_SOURCES: BroadcastSource[] = [
  {
    id: 'press-tv',
    name: 'Press TV',
    region: 'Middle East',
    country: 'Iran',
    language: 'English',
    category: 'State Media',
    sourceType: 'Satellite / Web',
    status: 'curated',
    streamUrl: 'https://live.presstv.ir/live/smil:live.smil/playlist.m3u8',
    homepageUrl: 'https://www.presstv.ir/',
    notes: 'English-language Iranian state broadcaster. Useful for regime framing and external messaging.',
    playbackMode: 'external_only',
    tags: ['news', 'state-media', 'middle-east', 'iran'],
    priority: 'best_effort',
    contentType: 'news',
  },
  {
    id: 'cgtn',
    name: 'CGTN',
    region: 'East Asia',
    country: 'China',
    language: 'English',
    category: 'State Media',
    sourceType: 'Satellite / Web',
    status: 'curated',
    streamUrl: 'https://news.cgtn.com/resource/live/english/cgtn-news.m3u8',
    homepageUrl: 'https://www.cgtn.com/',
    notes: 'Chinese external messaging channel. Track narrative positioning around technology, Taiwan, and trade.',
    playbackMode: 'external_only',
    tags: ['news', 'state-media', 'china', 'east-asia'],
    priority: 'best_effort',
    contentType: 'news',
  },
  {
    id: 'cctv4',
    name: 'CCTV-4',
    region: 'East Asia',
    country: 'China',
    language: 'Mandarin',
    category: 'State Media',
    sourceType: 'Satellite / Web',
    status: 'monitor',
    streamUrl: 'https://cctvtxyh5ca.liveplay.myqcloud.com/live/cctv4_2/index.m3u8',
    homepageUrl: 'https://tv.cctv.com/live/cctv4/',
    notes: 'Mandarin-language channel for domestic and diaspora signals.',
    playbackMode: 'unknown',
    tags: ['news', 'state-media', 'china', 'mandarin'],
    priority: 'unstable',
    contentType: 'news',
  },
  {
    id: 'rt-international',
    name: 'RT International',
    region: 'Russia / Eurasia',
    country: 'Russia',
    language: 'English',
    category: 'State Media',
    sourceType: 'Satellite / Web',
    status: 'monitor',
    streamUrl: 'https://rt-glb.rttv.com/live/rtnews/playlist.m3u8',
    homepageUrl: 'https://www.rt.com/on-air/',
    notes: 'Russian external messaging. Availability varies by jurisdiction and sanctions environment.',
    playbackMode: 'unknown',
    tags: ['news', 'state-media', 'russia', 'eurasia'],
    priority: 'unstable',
    contentType: 'news',
  },
  {
    id: 'trt-world',
    name: 'TRT World',
    region: 'Turkey / Eastern Med',
    country: 'Turkey',
    language: 'English',
    category: 'State Media',
    sourceType: 'Satellite / Web',
    status: 'curated',
    streamUrl: 'https://tv-trtworld.live.trt.com.tr/master.m3u8',
    homepageUrl: 'https://www.trtworld.com/live',
    notes: 'Turkish international broadcaster. Useful for Ankara framing, regional balancing, and NATO signaling.',
    playbackMode: 'external_only',
    tags: ['news', 'state-media', 'turkey', 'eastern-med'],
    priority: 'best_effort',
    contentType: 'news',
  },
  {
    id: 'dd-news',
    name: 'DD News',
    region: 'South Asia',
    country: 'India',
    language: 'English / Hindi',
    category: 'Public Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'monitor',
    streamUrl: 'https://d7x8z4yuq42qn.cloudfront.net/index_3.m3u8',
    homepageUrl: 'https://www.youtube.com/@DDNewsOfficial',
    notes: 'Indian state broadcaster. Useful for domestic-line messaging and official posture shifts.',
    playbackMode: 'unknown',
    tags: ['news', 'public-broadcaster', 'india', 'south-asia'],
    priority: 'unstable',
    contentType: 'news',
  },
  {
    id: 'al-jazeera-english',
    name: 'Al Jazeera English',
    region: 'Middle East',
    country: 'Qatar',
    language: 'English',
    category: 'Regional Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'curated',
    streamUrl: 'https://live-hls-web-aje.getaj.net/AJE/index.m3u8',
    homepageUrl: 'https://www.aljazeera.com/live/',
    notes: 'Regional reference source for Gulf, conflict, and diplomatic framing.',
    playbackMode: 'external_only',
    tags: ['news', 'reference', 'middle-east', 'qatar'],
    priority: 'best_effort',
    contentType: 'news',
  },
  {
    id: 'al-arabiya',
    name: 'Al Arabiya',
    region: 'Middle East',
    country: 'Saudi Arabia',
    language: 'Arabic',
    category: 'Regional Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'monitor',
    streamUrl: 'https://mbn-ingest-worldsafe.akamaized.net/hls/live/2038900/MBN_Alhurra_Worldsafe_HLS/master.m3u8',
    homepageUrl: 'https://www.alarabiya.net/',
    notes: 'Saudi-aligned regional framing. Useful comparative source alongside Qatari and Iranian outlets.',
    playbackMode: 'unknown',
    tags: ['news', 'reference', 'middle-east', 'saudi-arabia'],
    priority: 'unstable',
    contentType: 'news',
  },
  {
    id: 'dw-english',
    name: 'DW English',
    region: 'Europe',
    country: 'Germany',
    language: 'English',
    category: 'Public Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'curated',
    streamUrl: 'https://dwamdstream103.akamaized.net/hls/live/2015526/dwstream103/index.m3u8',
    homepageUrl: 'https://www.dw.com/en/live-tv/s-100825',
    notes: 'European reference feed. Useful for comparative narrative analysis and policy framing.',
    playbackMode: 'external_only',
    tags: ['news', 'public-broadcaster', 'reference', 'europe'],
    priority: 'best_effort',
    contentType: 'news',
  },
  {
    id: 'france24-english',
    name: 'France 24 English',
    region: 'Europe',
    country: 'France',
    language: 'English',
    category: 'Public Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'curated',
    streamUrl: 'https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8',
    homepageUrl: 'https://www.france24.com/en/live',
    notes: 'European international broadcaster with strong Africa, Middle East, and EU diplomatic coverage.',
    playbackMode: 'external_only',
    tags: ['news', 'public-broadcaster', 'reference', 'europe'],
    priority: 'best_effort',
    contentType: 'news',
  },
  {
    id: 'sky-news-arabia',
    name: 'Sky News Arabia',
    region: 'Middle East',
    country: 'UAE',
    language: 'Arabic',
    category: 'Regional Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'monitor',
    streamUrl: 'https://stream.skynewsarabia.com/ott/stream.m3u8',
    homepageUrl: 'https://www.skynewsarabia.com/live-stream',
    notes: 'UAE-aligned Gulf narrative reference point.',
    playbackMode: 'unknown',
    tags: ['news', 'reference', 'middle-east', 'uae'],
    priority: 'unstable',
    contentType: 'news',
  },
  {
    id: 'bbc-world-news',
    name: 'BBC World News',
    region: 'Europe',
    country: 'United Kingdom',
    language: 'English',
    category: 'Public Broadcaster',
    sourceType: 'Satellite / Web',
    status: 'monitor',
    streamUrl: 'https://vs-cmaf-pushb-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_world_news/mobile_wifi_main_sd_abr_v2/master.m3u8',
    homepageUrl: 'https://www.bbc.com/news/av/10462520',
    notes: 'Reference baseline for UK / Western institutional framing.',
    playbackMode: 'unknown',
    tags: ['news', 'public-broadcaster', 'reference', 'uk'],
    priority: 'unstable',
    contentType: 'news',
  },
  {
    id: 'fifa-plus',
    name: 'FIFA+',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'Sports Broadcaster',
    sourceType: 'OTT / Web',
    status: 'curated',
    streamUrl: 'https://www.plus.fifa.com/',
    homepageUrl: 'https://www.plus.fifa.com/',
    notes: 'Best-effort public football source. Often offers free live matches, replays, and federation coverage by territory.',
    playbackMode: 'external_only',
    tags: ['sports', 'football', 'global', 'public'],
    priority: 'verified',
    contentType: 'sports',
    sport: 'football',
  },
  {
    id: 'fifa-plus-youtube',
    name: 'FIFA YouTube',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'Sports Broadcaster',
    sourceType: 'YouTube',
    status: 'curated',
    streamUrl: 'https://www.youtube.com/@FIFA',
    homepageUrl: 'https://www.youtube.com/@FIFA',
    notes: 'Public football clips and occasional live event coverage. Stable external fallback.',
    playbackMode: 'external_only',
    tags: ['sports', 'football', 'youtube', 'public'],
    priority: 'verified',
    contentType: 'sports',
    sport: 'football',
  },
  {
    id: 'one-football',
    name: 'OneFootball Live',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'Sports Platform',
    sourceType: 'OTT / Web',
    status: 'monitor',
    streamUrl: 'https://onefootball.com/',
    homepageUrl: 'https://onefootball.com/',
    notes: 'Best-effort public football platform. Match availability varies by country and rights window.',
    playbackMode: 'external_only',
    tags: ['sports', 'football', 'public', 'best-effort'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'football',
  },
  {
    id: 'nba-app',
    name: 'NBA App / TV',
    region: 'Americas',
    country: 'United States',
    language: 'English',
    category: 'Sports Broadcaster',
    sourceType: 'OTT / Web',
    status: 'monitor',
    streamUrl: 'https://www.nba.com/watch',
    homepageUrl: 'https://www.nba.com/watch',
    notes: 'Public basketball portal. Free content is common, live games are territory-dependent and often limited.',
    playbackMode: 'external_only',
    tags: ['sports', 'basketball', 'public', 'best-effort'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'basketball',
  },
  {
    id: 'fiba-youtube',
    name: 'FIBA YouTube',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'Sports Broadcaster',
    sourceType: 'YouTube',
    status: 'curated',
    streamUrl: 'https://www.youtube.com/@FIBA',
    homepageUrl: 'https://www.youtube.com/@FIBA',
    notes: 'Public international basketball source with streams, replays, and tournament content.',
    playbackMode: 'external_only',
    tags: ['sports', 'basketball', 'youtube', 'public'],
    priority: 'verified',
    contentType: 'sports',
    sport: 'basketball',
  },
  {
    id: 'ufc-youtube',
    name: 'UFC YouTube',
    region: 'Americas',
    country: 'United States',
    language: 'English',
    category: 'Combat Sports',
    sourceType: 'YouTube',
    status: 'curated',
    streamUrl: 'https://www.youtube.com/@ufc',
    homepageUrl: 'https://www.youtube.com/@ufc',
    notes: 'Public combat sports source. Useful for weigh-ins, prelim coverage, and official live shoulder content.',
    playbackMode: 'external_only',
    tags: ['sports', 'combat', 'youtube', 'public'],
    priority: 'verified',
    contentType: 'sports',
    sport: 'combat',
  },
  {
    id: 'one-championship',
    name: 'ONE Championship',
    region: 'East Asia',
    country: 'Singapore',
    language: 'English',
    category: 'Combat Sports',
    sourceType: 'OTT / Web',
    status: 'monitor',
    streamUrl: 'https://www.onefc.com/watch/',
    homepageUrl: 'https://www.onefc.com/watch/',
    notes: 'Best-effort public combat source with region-dependent event access.',
    playbackMode: 'external_only',
    tags: ['sports', 'combat', 'asia', 'best-effort'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'combat',
  },
  {
    id: 'formula-e',
    name: 'Formula E',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'Motorsport',
    sourceType: 'OTT / Web',
    status: 'monitor',
    streamUrl: 'https://www.fiaformulae.com/en/watch/ways-to-watch',
    homepageUrl: 'https://www.fiaformulae.com/en/watch/ways-to-watch',
    notes: 'Motorsport rights map and occasional public streams by territory.',
    playbackMode: 'external_only',
    tags: ['sports', 'motorsport', 'public', 'best-effort'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'motorsport',
  },
  {
    id: 'red-bull-tv',
    name: 'Red Bull TV',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'General Sports',
    sourceType: 'OTT / Web',
    status: 'curated',
    streamUrl: 'https://www.redbull.com/int-en/live',
    homepageUrl: 'https://www.redbull.com/int-en/live',
    notes: 'Stable public sports platform with live action, motorsport, cycling, and outdoor events.',
    playbackMode: 'external_only',
    tags: ['sports', 'general', 'motorsport', 'public'],
    priority: 'verified',
    contentType: 'sports',
    sport: 'general',
  },
  {
    id: 'olympics',
    name: 'Olympics Channel',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'General Sports',
    sourceType: 'OTT / Web',
    status: 'monitor',
    streamUrl: 'https://olympics.com/en/live/',
    homepageUrl: 'https://olympics.com/en/live/',
    notes: 'Best-effort public multi-sport feed with event-dependent availability.',
    playbackMode: 'external_only',
    tags: ['sports', 'general', 'public', 'best-effort'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'general',
  },
  {
    id: 'mls-youtube',
    name: 'MLS YouTube',
    region: 'Americas',
    country: 'United States',
    language: 'English',
    category: 'Sports Broadcaster',
    sourceType: 'YouTube',
    status: 'monitor',
    streamUrl: 'https://www.youtube.com/@MLS',
    homepageUrl: 'https://www.youtube.com/@MLS',
    notes: 'Best-effort football source for highlights, shoulder content, and occasional live coverage.',
    playbackMode: 'external_only',
    tags: ['sports', 'football', 'americas', 'youtube'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'football',
  },
  {
    id: 'bein-sports-xtra',
    name: 'beIN SPORTS XTRA',
    region: 'Middle East',
    country: 'Qatar',
    language: 'English / Arabic',
    category: 'Sports Broadcaster',
    sourceType: 'FAST / Web',
    status: 'monitor',
    streamUrl: 'https://www.beinsports.com/us/watch/channel/bein-sports-xtra',
    homepageUrl: 'https://www.beinsports.com/us/watch/channel/bein-sports-xtra',
    notes: 'Best-effort public sports channel. Availability depends on region and current FAST carriage.',
    playbackMode: 'external_only',
    tags: ['sports', 'general', 'middle-east', 'best-effort'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'general',
  },
  {
    id: 'moto-gp',
    name: 'MotoGP VideoPass',
    region: 'Europe',
    country: 'Global',
    language: 'English',
    category: 'Motorsport',
    sourceType: 'OTT / Web',
    status: 'monitor',
    streamUrl: 'https://www.motogp.com/',
    homepageUrl: 'https://www.motogp.com/',
    notes: 'Motorsport source with public content and rights-dependent live windows.',
    playbackMode: 'external_only',
    tags: ['sports', 'motorsport', 'best-effort', 'public'],
    priority: 'best_effort',
    contentType: 'sports',
    sport: 'motorsport',
  },
];

export const BROADCAST_REGIONS = [
  'All Regions',
  'Middle East',
  'East Asia',
  'Russia / Eurasia',
  'Turkey / Eastern Med',
  'South Asia',
  'Europe',
  'Americas',
] as const;

export const BROADCAST_CONTENT_FILTERS = ['All', 'News / State', 'Sports'] as const;

export const BROADCAST_SPORT_FILTERS = [
  'All Sports',
  'Football',
  'Basketball',
  'Combat',
  'Motorsport',
  'General',
] as const;